language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
service: docker
env:
  global:
  - secure: aV4qXEVTbvMKrb7IlRGBsMqO4T47nNEA6XDY/EDNqXQtmliNmfowxFE8LPM75GqadZIluedtV++WD8hq2ULdbBLQ/KsRsPtE54yz/iPM7nWRNHVSiyKlYn088Z0mTuDWrbmwtl1rSO5WWnARxTecAZpbJl7oMr/VDGBM4QM2NjRuiciRXNVRXrpXVFYpCzhGxBw28i4ZFeyUjq+iCDoIxMT/OFaddOAx70gmPi5LH/YtxTQWOwgqtBP8Fk3tIjSdERQias8NvBs2qBAnF6qDTtWgKvLuvI4CcpN2OokBSzZKgdzl13Vj/7QsbTs2jsNQgRQ0M9+RQTX3KTzVIF5WJJ8reXzgfE/aNSqMqFHXGmh010Is9A2JIzDnwzkkpSnYOrXx7o1pZw4Iv9Y9mYPWJMZpfo0ZAG6XLWXZ85WemOJ4R1DAJm9QBaOG1PnZtGUA0JpvGIrz6SzXbbDOheJTm28Ajw09CbFXb2i6fuCRX6XIu4H9Ev75tZpbtLboxFeFNy9zb/pFu8FjPG+6dxNoXi9KFPGb263V3hwWwOofiL7cfXwhdDweCyEKoo6Z256dTQbOz5/GzMn4bwN7rfDPAKERiu0sXJiiO02lqbHG5SsL5Lw8NlukfC2p2MBMkYZHyYo4cI85nCsZDeED7NDjyzyoBfn2SaY2qIATGsqM4hU=
  - secure: IdRgaELDNU5cmraZ80D45pA9nbsj2L8LZf178lwT4Np8pJ/EeM4vlyeCHPBRn6MTWS383OpqEhgGSbTOerJGsaDRaWNI/5S9O9XKql/oV5K9p71HU/AqiR6RpdOeNRxx/fn/EtOIx43sBBhzRIPg4a4QfhsXGR+v/NDmHpABtstgLSru9JsqA0/ZQYP2W2kUZyBMCom9cnfL0rsFzrgcXplaYNxiJc9zUPmGNwCbhT8tlk+EFx/Of38hsDYMaqLgXPzJ0WVE4PrDH8VnazYh+hFrDBW6s2KkojnddzbZ/Vf95hdgCNawAwq8czl5doVOB65x9Cl/VLqlsKAh1Cdz+MboSUJdsaANvhKQBLm6I2W2XI4JhxTwkSLkzMuOORO+0B0EKiPTi9NgXD0HYSYUiGSpNC+U+upv0lvCO66zVS206LScuY8ijn5THZ7XTpF+Q+WOPef9eoavCixs6Uo3QdvjN0RpNnuxy1h5Ld/v5a20dvP9XIz9XH1het3UskR0WVvy36rpnB+QkQozSzPIrEM5R1SIHiydxHE1kCXcmUa7kBcejfUNwpPUwH7SfnDr4TVA6T375/nABJV4OYHkgerCtbV2zPzGwyuVGYTlIquuBENy7lrvnsucFyH6yOsBHxmCZ9o/rCLxKPCNw13brMxdLmh4q45ZkAD+IKSfOAk=
  - secure: C7aZSqkI0LddvK04gFl0fHZMBsgGZpA+qjsb/Bg7llZCmXGF6yM0lF4NUOOkDFLh7M6nS8RuWK5yGwxYjq0sgEuxApJacPdaZFLscxud4jY9pUwpnZ5y9M+F/BKaDiByaJ+eKFlCfMs/awtE97gGtp6IzwwmYKQYfLReBJl7TPsCS7MK+0wPBwOAg4PTVulbQtuz4mTn5RV6blj5cEZofwj2z5RsbmztnSJtDTDSkLmdojrPdszZjT3k3l32XqxkR9o1j72NMZVfPPTwdPZ4qWXJcVFHvK5qCD/XUMYsfFP2ZL+J4LR0ih2XskGbthJ29FmjcFIi4Q+MnoX+VJLaRtL+bml93xx9lHWXQEZBO6VfaBZ6SbWZjWu9HdrTU4R8jrF3ZzDtUVgFOsJhR54SHsD5NaMimR4VtwSrIucEyQUGfBXJtU9oElMIDHQYfGWmRzGl6BjGQGwiuPwqkxr3ebaO41eAlxA5+5QlcaokqlA1JBXDpiV89FbhS1avPq70daFWentTMxYVkkKZnLTnMgPB0mvziJAzkpegZKXVdMUPEhg2/npbQQ8X24OBcwqFp+ncxXTtEGn1DDWP2WXRQ0ijUZJOUZ0O2VU1JvoQxtz2zGdfuBfOjLKKdfBAVf3OcbIWRsWGFwsEEZlvufN8tbCNkuLvC5AuoClddQiLGV4=
